### ISSUE TITLE
After log in pop ups

### ISSUE THREAD

**Issue by arcayne** [roti-project/ZenRoti#2]
We want to show relevant info after logging in 2 scenarios:

* The user did not integrate / connected slack, therefore it is not an active user.
* On the onboarding we can show what are the first steps 

Maybe those 2 points can be summed up in one as the integration to slack is the key activity.

An active user does not get any pop up.

- Pop up system based on active user
- Pop up design copy , images

**Comment by blanxii** [comment]
![Screenshot 2020-09-30 at 17.46.44.png](https://images.zenhubusercontent.com/5e902913ed4490a699e9a9e2/2bd56212-d4d8-4641-ae03-ef8aca6eb0bd)

Popup added with the welcome message (also we can do something with the admin, maybe a gif helps much more to see the steps, add the verification on the same modal could be some problems, it's up to you @arcayne if we want that on the popup).

**Comment by blanxii** [comment]
(btw to emulate this just add ?welcome on the user page, do we want the same for the admin?)

**Comment by blanxii** [comment]
As an admin:

ADMIN: Button to link to SLACK account.

USER/ADMIN: When it's done button to link myself

ADMIN: Invite people (Skip)

USER/ADMIN: Explanation.
